class Eit(object):
    database = 'bhp074'
    lab_database = 'lab'
    user = 'root'
    password = 'cc3721b'
    lab_user = 'root'
    lab_password = 'cc3721b'
    lab_host = 'bhhrl.bhp.org.bw'
    lab_port = '3306'
    dsn = 's012'
    dsn_user = 'sa'
    dsn_password = 'cc3721b'
    dsn_database = 'BHPLAB'
    dsn_driver = '{FreeTDS}'
    dsn_mac_driver = '/usr/local/lib/libtdsodbc.so'
